<?php
/**
* Implementation of hook_form_alter()
*/
function hosting_san_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'site_node_form') {
    $form['san'] = array(
      '#type' => radios',
      '#title' => t('Enable Service Alternate Names (SANs)'),
      '#options' => hosting_san_options(),
      '#description' => t('Is the domain contained within an SSL containing a SAN for this domain?'),
      '#required' => TRUE,
      '#default_value' => (isset($node->san_enabled)) ? node->san_enabled : HOSTING_SAN_DISABLED,
      '#access' => user_access('administer_ssl),
      '#weight' => 0,
    );
    return $form;
  }
}
/** 
* Implementation of hook_insert()
*/
function hosting_san_insert($node) {
  if ($node->san) {
    db_query("INSERT INTO {hosting_san} (vid, nid, san) VALUES (%d, %d, '%s')", $node->vid, $node->nid, $node->san);
  }
}
/**
* Implementation of hook_update()
*/
function hosting_san_update($node) {
  db_query("UPDATE {hosting_san} SET san = '%s' WHERE nid = %d", $node->san, $node->nid);
}
/**
* Implementation of hook_delete()
*/
function hosting_san_delete($node) {
  db_query("DELETE FROM {hosting_san} WHERE nid=%d", $node->nid);
}
/**
* Implementation of hook_delete_revision()
*/
function hosting_san_delete_revision($node) {
  db_query("DELETE FROM {hosting_san} WHERE vid=%d", $node->vid);
}
/** 
* Implementation of hook_nodeapi()
*/
function hosting_san_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  if ($node->type == 'site') {
    switch ($op) {
    case 'insert':
        hosting_san_insert($node);
        break;
      case 'update':
        hosting_san_update($node);
        break;
      case 'delete' :
        hosting_san_delete($node);
        break;
      case 'delete revision':
        hosting_san_delete_revision($node);
        break;
      case 'validate' :
        if (!$node->san) {
          form_set_error('san', t('You must enter a SAN!'));
        }
        break;
      case 'load':
        $additions['san'] = db_result(db_query("SELECT san FROM {hosting_san} WHERE vid=%d", $node->vid));
        return $additions;
        break;
    }
  }
}
?>
